### ISSUE TITLE
u"Key 'order' not found

### ISSUE THREAD

**Issue by gbcgit** [jrief/django-admin-sortable2#104]
KeyError at /admin/pages/project/2/change/
u"Key 'order' not found in 'ProjectForm'"

For a Model I have named Project.  This is the form the Admin created, nothing I created.

The order field was in the fieldsets.  When I added the field to readonly_fields, the error cleared up.

You might want to add some meaningful error handling to say something like:  "Put that field in readonly, or remove from fieldsets."  And, or, at least, noting in your docs.  (Although, perhaps this issue is documentation enough.)

**Comment by jrief** [comment]
That's a good point. Can you please send me the full backtrace, so that I know where to add it.

**Comment by gbcgit** [comment]
Traceback (most recent call last):
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 167, in render
    values = list(values)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 112, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 123, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/forms/forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'order' not found in 'ProjectForm'"
Internal Server Error: /admin/pages/project/2/change/
Traceback (most recent call last):
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/loader_tags.py", line 209, in render
    return template.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/template/defaulttags.py", line 167, in render
    values = list(values)
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 112, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 123, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "/Users/gbc/virtualenvs/calmat_ng/lib/python2.7/site-packages/django/forms/forms.py", line 144, in __getitem__
    "Key %r not found in '%s'" % (name, self.__class__.__name__))
KeyError: u"Key 'order' not found in 'ProjectForm'"

**Comment by jrief** [comment]
@gbcgit 
Just for clarity, this happened for an ``SortableAdminMixin`` and not for a ``SortableInlineAdminMixin``? I'm asking because I had the same issue with the ``SortableInlineAdminMixin`` today.

**Comment by gbcgit** [comment]
Yes, SortableAdminMixin. Not sure if I've seen it with SortableInlineAdminMixin.  I will post if I do.

**Comment by rubengrill** [comment]
If you got this error with `SortableInlineAdminMixin` it is fixed in #107

**Comment by jrief** [comment]
close via #107
