### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one -- it returned 2!

### ISSUE THREAD

**Issue by nachopro** [jrief/django-admin-sortable2#175]
When I add a new object to my model, it saves a index = 0, then when I try to sort it I get this error:

```python
Internal Server Error: /admin/showcases/showcase/adminsortable2_update/
Traceback (most recent call last):
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/adminsortable2/admin.py", line 200, in update_order
    moved_items = list(self._move_item(request, startorder, endorder))
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/adminsortable2/admin.py", line 259, in _move_item
    obj = self.model.objects.get(**filters)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Showcase -- it returned 2!
```

My settings.py:

```python
INSTALLED_APPS = [
    ...
    'adminsortable2',
    ...
]
```

My model:

```python
class Showcase(PolymorphicModel, AuditModel):
    title = models.CharField(max_length=100)

    index = models.PositiveIntegerField(default=0)
    is_enabled = models.BooleanField(default=True)

    class Meta:
        ordering = ('index',)
```

To "solve" this issue I must edit all objects with non used index value.

**Comment by jrief** [comment]
this is presumably because of an inconsistency in the order field.
This is caused by other problems, for instance if the field is updated from someone else.

I now added a better explanation what to do in such a situation.

**Comment by nachopro** [comment]
Sorry, but where is the explanation to fix this issue?

Thanks you!

**Comment by nachopro** [comment]
May this related to use 
```
class ShowcaseAdmin(SortableAdminMixin, PolymorphicParentModelAdmin):
```
??
