### ISSUE TITLE
Is this module compatible with django-polymorphic?

### ISSUE THREAD

**Issue by nachopro** [jrief/django-admin-sortable2#196]
Hi, I'm using sortable2 in this way:

Model:
```python
class Showcase(PolymorphicModel):
    title = models.CharField(max_length=100)

    index = models.PositiveIntegerField(default=0)
    is_enabled = models.BooleanField(default=True)

    class Meta:
        ordering = ('index',)

    objects = EnabledManager()

    def __unicode__(self):
        return u'{} ({})'.format(self.title, u'✔' if self.is_enabled else u'✘')
```

Admin:
```python
@admin.register(Showcase)
class ShowcaseAdmin(SortableAdminMixin, PolymorphicParentModelAdmin):
    base_model = Showcase
    child_models = (ShowcaseStatus, ShowcaseFeatured, ShowcaseDynamic,
                    ShowcaseAd)
    list_filter = (PolymorphicChildModelFilter,)

    list_display = (
        'title',
        'polymorphic_ctype',
        'is_enabled'
    )
```
Steps:
I add two registers (without assigning value to `index`).
I sort them.
Refresh the admin page.

Sort unapplyed.

Here a screenshot https://imgur.com/a/mDNARoN

**Comment by jrief** [comment]
You have to add the `SortableAdminMixin` to all of the child classes, for instance

```
@admin.register(Showcase)
class ShowcaseAdmin(SortableAdminMixin, PolymorphicChildModelAdmin):
    ...
```

**Comment by nachopro** [comment]
Thanks for your response. I added the mixin to the Childs model. 
Now the problem comes when I try to sort mixed objects from the Parent admin.

```
Internal Server Error: /admin/showcases/showcase/adminsortable2_update/
Traceback (most recent call last):
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/adminsortable2/admin.py", line 193, in update_order
    moved_items = list(self._move_item(request, startorder, endorder))
  File "/home/nachopro/.virtualenvs/rootinks/lib/python2.7/site-packages/adminsortable2/admin.py", line 258, in _move_item
    raise self.model.MultipleObjectsReturned(msg.format(self.default_order_field, self.model._meta.label))
MultipleObjectsReturned: Detected non-unique values in field 'index' used for sorting this model.
Consider to run 
    python manage.py reorder showcases.Showcase
to adjust this inconsistency.
```

**Comment by jrief** [comment]
well, then
```
Consider to run 
    python manage.py reorder showcases.Showcase
to adjust this inconsistency.
```

:)

**Comment by nachopro** [comment]
I guess the problem comes whem the `max_order` is computed on a Child repeating a index from other Child from the same parent.

Appending new records to the same Child works fine.
I tryied using `PolymorphicSortableAdminMixin` but fails too.

PS: Run `./manage.py reorder showcases.Showcase` after every record that been added is not the best solution (IMHO).

**Comment by nachopro** [comment]
Let my clarify my concept:

I have a Parent model (`Showcase`) and four Child that inherits from him (`ShowcaseFeatured`, `ShowcaseAd`, `ShowcaseDynamic` and `ShowcaseStatus`)**.

I want to create many records from differents kind (**) and sort them across the `Showcase`'s ModelAdmin listing

Is this behavior supported by adminsortable2?

Thanks for your time.

**Comment by nachopro** [comment]
@jrief after analyzation of your code, my solution was achieved by a signal.
I know that my case is very special and it is complicated to cover all cases.

Thanks for your time!

```python
@receiver(post_save, sender=ShowcaseStatus)
@receiver(post_save, sender=ShowcaseFeatured)
@receiver(post_save, sender=ShowcaseDynamic)
@receiver(post_save, sender=ShowcaseAd)
def override_sort(sender, instance, created, **kwargs):
    if hasattr(instance, '_avoid_signal'):
        return

    instance._avoid_signal = True
    try:
        if created or instance.index == 0:
            next_index = Showcase.objects.aggregate(Max('index'))['index__max']
            instance.index = next_index + 1
            instance.save()

    finally:
        del instance._avoid_signal
```

**Comment by jrief** [comment]
so you found a solution yourself? Can I close this then?
