### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by Joaquinecc** [jrief/django-admin-sortable2#279]
$ pipenv  install django-admin-sortable2
Installing django-admin-sortable2…
Adding django-admin-sortable2 to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock (c33584) out of date, updating to (f98f60)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
           Building requirements...
Resolving dependencies...
Locking Failed!
Traceback (most recent call last):
  File "c:/users/euli/appdata/local/programs/python/python36/lib/site-packages/pipenv/resolver.py", line 807, in <module>   
    main()
  File "c:/users/euli/appdata/local/programs/python/python36/lib/site-packages/pipenv/resolver.py", line 803, in main       
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "c:/users/euli/appdata/local/programs/python/python36/lib/site-packages/pipenv/resolver.py", line 785, in _main      
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "c:/users/euli/appdata/local/programs/python/python36/lib/site-packages/pipenv/resolver.py", line 758, in resolve_packages
    results = clean_results(results, resolver, project)
  File "c:/users/euli/appdata/local/programs/python/python36/lib/site-packages/pipenv/resolver.py", line 634, in clean_results
    reverse_deps = project.environment.reverse_dependencies()
  File "c:\users\euli\appdata\local\programs\python\python36\lib\site-packages\pipenv\project.py", line 374, in environment 
    self._environment = self.get_environment(allow_global=allow_global)
  File "c:\users\euli\appdata\local\programs\python\python36\lib\site-packages\pipenv\project.py", line 364, in get_environment
    environment.extend_dists(pipenv_dist)
  File "c:\users\euli\appdata\local\programs\python\python36\lib\site-packages\pipenv\environment.py", line 123, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "c:\users\euli\appdata\local\programs\python\python36\lib\site-packages\pipenv\environment.py", line 118, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "c:\users\euli\appdata\local\programs\python\python36\lib\site-packages\pipenv\environment.py", line 117, in resolve_dist
    dist = working_set.find(req)
  File "C:\Users\Euli\.virtualenvs\laberinfo-backend-zbhLVtwY\lib\site-packages\pkg_resources\__init__.py", line 628, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 4.0.1 (c:\users\euli\.virtualenvs\laberinfo-backend-zbhlvtwy\lib\site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))

**Comment by Joaquinecc** [comment]
It was a problem with pipenv.
Solve by jus running
pip install -U pipenv
