### ISSUE TITLE
ImportError: No module named adminsortable

### ISSUE THREAD

**Issue by matiasbenedetto** [jrief/django-admin-sortable2#33]
Hi, im using Django 1.7 and im geting this error when in run python manage.py runserver:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/matias/env/sudestada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/matias/env/sudestada/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/home/matias/env/sudestada/local/lib/python2.7/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/matias/env/sudestada/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/matias/env/sudestada/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named adminsortable

**Comment by Zowie** [comment]
I have exactly the same issue. Django 1.7.4 on Python 3, first i thought it was a django-admin-sortable/django-admin-sortable2 conflict but after trying it in a fresh virtualenv the issue remained. 

Strange thing is, i can actually import using `adminsortable2.admin`, though my IDE complains the module isn't there. Of course, the admin site fails immediately because it's using `adminsortable` for all paths, and not `adminsortable2`. I'm going to try to work around this quickly by renaming a lot of stuff, and will post other findings here.

**Comment by Zowie** [comment]
Installed from master branch where all the package names are changed, only thing left was to modify the `stacked` templates. #51

**Comment by jrief** [comment]
Please note that since version 0.5.0 adminsortable has been renamed to adminsortable2 to allow a soft migration from django-admin-sortable (the project I wanted to replace).

**Comment by agilealpha1** [comment]
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'adminsortable2'

**Comment by kacash** [comment]
With django 1.11.26:
```
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'adminsortable2'
```
