### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by AndreyMZ** [jrief/django-admin-sortable2#367]
### Steps to reproduce
Follow the guide "[Run the Demo App](https://django-admin-sortable2.readthedocs.io/en/latest/contributing.html#run-the-demo-app)" until the step `./manage.py migrate` inclusive.

#### Actual result
~~~
(django-admin-sortable2) PS C:\django-admin-sortable2\testapp> ./manage.py migrate
C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\models\base.py:321: RuntimeWarning: Model 'testapp.book1' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\models\base.py:321: RuntimeWarning: Model 'testapp.book2' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, testapp                                                                                         
Running migrations:                                                                                                                                          
  No migrations to apply.                                                                                                                                    
Traceback (most recent call last):                                                                                                                           
  File "C:\django-admin-sortable2\testapp\manage.py", line 23, in <module>                                                                               
    main()                                                                                                                                                   
  File "C:\django-admin-sortable2\testapp\manage.py", line 19, in main                                                                                   
    execute_from_command_line(sys.argv)                                                                                                                      
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\base.py", line 417, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\core\management\commands\migrate.py", line 236, in handle
    changes = autodetector.changes(graph=executor.loader.graph)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\autodetector.py", line 156, in _detect_changes
    self.to_state.resolve_fields_and_relations()
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 449, in resolve_fields_and_relations
    concretes, proxies = self._get_concrete_models_mapping_and_proxy_models()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 470, in _get_concrete_models_mapping_and_proxy_models
    concrete_models_mapping[model_key] = self._find_concrete_model_from_proxy(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 486, in _find_concrete_model_from_proxy
    return self._find_concrete_model_from_proxy(proxy_models, base_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 486, in _find_concrete_model_from_proxy
    return self._find_concrete_model_from_proxy(proxy_models, base_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 486, in _find_concrete_model_from_proxy
    return self._find_concrete_model_from_proxy(proxy_models, base_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 983 more times]
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\migrations\state.py", line 481, in _find_concrete_model_from_proxy
    base_key = make_model_tuple(base)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\django-admin-sortable2\Lib\site-packages\django\db\models\utils.py", line 16, in make_model_tuple
    model_tuple = app_label, model_name.lower()
                             ^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
~~~

#### Expected result
No such error.

### Additional information
The version of django-admin-sortable2 was [396aadaa](https://github.com/jrief/django-admin-sortable2/tree/396aadaa1d5bde4562a54c2be1b996b1b98ab315).
I tried with Django 4.2, 4.1, and 4.0.

**Comment by AndreyMZ** [comment]
I don't know why, but the problem has disappeared after repeating the steps again from scratch.
